@BearerToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJHdWkxIiwiaWF0IjoxNzY1MzA2MTIxLCJleHAiOjE3NjUzMDYzNjEsInJvbGUiOiJBRE1JTiJ9.fDLtZUeq4EvSG_8eOmTgmhb2y3dxrzpjRcoycd3vj0c

### Login
POST http://localhost:8888/api/auth
Content-Type: application/json

{
  "username": "Gui1",
  "password": "123456"
}


### Criar novo usuário
POST http://localhost:8888/api/usuarios
Content-Type: application/json

{
  "email": "tiger@gmail.com",
  "username": "Tiger",
  "password": "123456"
}


### Listar usuários
GET http://localhost:8888/api/usuarios
Authorization: Bearer {{BearerToken}}
Content-Type: application/json
